[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.124.0"
    HUGO_THEME = "hugo-theme-stack"

[context.production]
    command = "hugo --gc --minify --baseURL $URL"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "hugo --gc --minify --baseURL $URL"

[context.deploy-preview]
    command = "hugo --gc --minify --baseURL $URL"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            srcdir = "/"
